name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1', 'nightly']
        arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            arch: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build
        uses: julia-actions/julia-buildpkg@v1

      - name: Test
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true

      - name: Create coverage file
        uses: julia-actions/julia-processcoverage@v1
      
      - name: Upload coverage to codevoc
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info